CREATE TABLE topicos (

  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  mensagem VARCHAR(250) NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL,
  autor VARCHAR(100) NOT NULL,
  curso VARCHAR(50) NOT NULL

);
